srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python getpotaDA2_mock.py --realization 0 --mock_version _v4_1
srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python getpotaDA2_mock.py --realization 1 --mock_version _v4_1
srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python getpotaDA2_mock.py --realization 2 --mock_version _v4_1
srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python getpotaDA2_mock.py --realization 3 --mock_version _v4_1
srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python getpotaDA2_mock.py --realization 4 --mock_version _v4_1
srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python getpotaDA2_mock.py --realization 5 --mock_version _v4_1
srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python getpotaDA2_mock.py --realization 6 --mock_version _v4_1
srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python getpotaDA2_mock.py --realization 7 --mock_version _v4_1
srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python getpotaDA2_mock.py --realization 8 --mock_version _v4_1
srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python getpotaDA2_mock.py --realization 9 --mock_version _v4_1
srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python getpotaDA2_mock.py --realization 10 --mock_version _v4_1
srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python getpotaDA2_mock.py --realization 11 --mock_version _v4_1
srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python getpotaDA2_mock.py --realization 12 --mock_version _v4_1
srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python getpotaDA2_mock.py --realization 13 --mock_version _v4_1
srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python getpotaDA2_mock.py --realization 14 --mock_version _v4_1
srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python getpotaDA2_mock.py --realization 15 --mock_version _v4_1
srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python getpotaDA2_mock.py --realization 16 --mock_version _v4_1
srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python getpotaDA2_mock.py --realization 17 --mock_version _v4_1
srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python getpotaDA2_mock.py --realization 18 --mock_version _v4_1
srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python getpotaDA2_mock.py --realization 19 --mock_version _v4_1
srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python getpotaDA2_mock.py --realization 20 --mock_version _v4_1
srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python getpotaDA2_mock.py --realization 21 --mock_version _v4_1
srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python getpotaDA2_mock.py --realization 22 --mock_version _v4_1
srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python getpotaDA2_mock.py --realization 23 --mock_version _v4_1
srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python getpotaDA2_mock.py --realization 24 --mock_version _v4_1
