
# file parameters for holi pipeline

#
# GENERAL PARAMETERS
#

# LSS  package, must include LSS at the end
LSS_dir = "/global/cfs/cdirs/desi/users/colley/LSS" 

# mocks output dir
mock_dir = "/pscratch/sd/j/jcolley/holi/webjax_v4.80"

# log directory
logs_dir = "/pscratch/sd/j/jcolley/holi/webjax_v4.80/slurm"

# 
input_ref = "/global/cfs/cdirs/desi/mocks/cai/holi/webjax_v4.80"
first_id = 301

# for debug else -1
max_gal= -1

#
# STEP PARAMETERS
#

[prepare_mocks] # step 1
#specdata = "loa-v1"
survey = "DA2"


[brickmask] # step 3
cfitsio = "/global/common/software/desi/users/naimgk/cfitsio"
exe_dir = "/global/cfs/cdirs/desi/users/colley/wd_brick/brickmask_mpi"
conf_dir = "/global/cfs/cdirs/desi/users/colley/LSS/scripts/mock_tools/holi_pipeline"


[init_amtl] # step 7
#amtl_dir = ""


[amtl] # step 8
#verbose=''
