
# file parameters for holi pipeline

#
# GENERAL PARAMETERS
#

# actualy holi pipeline always used a local version of LSS package
# NOTE: must include LSS at the end
LSS_dir = "/global/cfs/cdirs/desi/users/colley/LSS"
TARGET_dir= "/global/cfs/cdirs/desi/users/colley/desitarget"

# output directory of holi pipeline
# will content seed0000 and altmtl0000 directories
mock_dir = "/pscratch/sd/j/jcolley/test_hp"

# log directory
logs_dir = "/global/homes/j/jcolley/test/runs"

# reference simulation directory
input_ref = "/global/cfs/cdirs/desi/mocks/cai/holi/webjax_v4.80"

# First id seed processing by pipeline
first_id = 301

# for debug, reduce number of galaxy for fast processing,
# minimal value is 5000 else error can appears
# no limitation with value <0, like -1
max_gal = -1

#
# STEP PARAMETERS
#

[prepare_mocks] # step 1
#specdata = "loa-v1"
# example of prepare_mocks parameters, can be completed if necessary
survey = "DA2"


[brickmask] # step 3
cfitsio = "/global/common/software/desi/users/naimgk/cfitsio"
exe_dir = "/global/cfs/cdirs/desi/users/colley/wd_brick/brickmask_mpi"
conf_dir = "/global/cfs/cdirs/desi/users/colley/LSS/scripts/mock_tools/holi_pipeline"


[init_amtl] # step 7
#amtl_dir = ""


[amtl] # step 8
# verbose mode is '--verbose', by default ''
#verbose='--verbose'

# select desi/desi_environment.sh version 
desi_env_vers = '26.3'