# config
input_path: '../input/eBOSS.ELG.NGC.DR7.table.fits'
output_path: '../output/model_test' 
restore_model: null 
batch_size: 512
nepochs: 2
nchains: 1
find_lr: False
find_structure: False 
find_l1: False
do_kfold: False 
do_tar: False
snapshot_ensemble: False
normalization: 'z-score'
model: dnnp
optim: adamw
scheduler: cosann
axes: 
  - 0
  - 1 
  - 2
do_rfe: False
eta_min: 1.0e-5
learning_rate: 1.0e-3
nn_structure:
  - 4
  - 20
l1_alpha: -1.0  
loss: pnll
no_eval: False
