python mkCat_SV3_ran.py --type dark --cutran n --combr y --ranmtl n --rfa n --mockrea 1 --univ 2 --verspec fuji
python mkCat_SV3_ran.py --type dark --cutran n --combr y --ranmtl n --rfa n --mockrea 2 --univ 3 --verspec fuji
python mkCat_SV3_ran.py --type dark --cutran n --combr y --ranmtl n --rfa n --mockrea 3 --univ 4 --verspec fuji
python mkCat_SV3_ran.py --type dark --cutran n --combr y --ranmtl n --rfa n --mockrea 4 --univ 5 --verspec fuji
python mkCat_SV3_ran.py --type dark --cutran n --combr y --ranmtl n --rfa n --mockrea 5 --univ 6 --verspec fuji
python mkCat_SV3_ran.py --type dark --cutran n --combr y --ranmtl n --rfa n --mockrea 6 --univ 7 --verspec fuji
python mkCat_SV3_ran.py --type dark --cutran n --combr y --ranmtl n --rfa n --mockrea 7 --univ 8 --verspec fuji
python mkCat_SV3_ran.py --type dark --cutran n --combr y --ranmtl n --rfa n --mockrea 8 --univ 9 --verspec fuji
python mkCat_SV3_ran.py --type dark --cutran n --combr y --ranmtl n --rfa n --mockrea 9 --univ 10 --verspec fuji
python mkCat_SV3_ran.py --type dark --cutran n --combr y --ranmtl n --rfa n --mockrea 10 --univ 11 --verspec fuji
python mkCat_SV3_ran.py --type dark --cutran n --combr y --ranmtl n --rfa n --mockrea 11 --univ 12 --verspec fuji
python mkCat_SV3_ran.py --type dark --cutran n --combr y --ranmtl n --rfa n --mockrea 12 --univ 13 --verspec fuji
python mkCat_SV3_ran.py --type dark --cutran n --combr y --ranmtl n --rfa n --mockrea 13 --univ 14 --verspec fuji
python mkCat_SV3_ran.py --type dark --cutran n --combr y --ranmtl n --rfa n --mockrea 14 --univ 15 --verspec fuji
python mkCat_SV3_ran.py --type dark --cutran n --combr y --ranmtl n --rfa n --mockrea 15 --univ 16 --verspec fuji
python mkCat_SV3_ran.py --type dark --cutran n --combr y --ranmtl n --rfa n --mockrea 16 --univ 17 --verspec fuji
python mkCat_SV3_ran.py --type dark --cutran n --combr y --ranmtl n --rfa n --mockrea 17 --univ 18 --verspec fuji
python mkCat_SV3_ran.py --type dark --cutran n --combr y --ranmtl n --rfa n --mockrea 18 --univ 19 --verspec fuji
python mkCat_SV3_ran.py --type dark --cutran n --combr y --ranmtl n --rfa n --mockrea 19 --univ 20 --verspec fuji
python mkCat_SV3_ran.py --type dark --cutran n --combr y --ranmtl n --rfa n --mockrea 20 --univ 21 --verspec fuji
python mkCat_SV3_ran.py --type dark --cutran n --combr y --ranmtl n --rfa n --mockrea 21 --univ 22 --verspec fuji
python mkCat_SV3_ran.py --type dark --cutran n --combr y --ranmtl n --rfa n --mockrea 22 --univ 23 --verspec fuji
python mkCat_SV3_ran.py --type dark --cutran n --combr y --ranmtl n --rfa n --mockrea 23 --univ 24 --verspec fuji
python mkCat_SV3_ran.py --type dark --cutran n --combr y --ranmtl n --rfa n --mockrea 24 --univ 25 --verspec fuji
