python mkCat_SV3.py --type LRG --combd n --fulld y --clus y --mockrea 0 --univ 1 --verspec fuji --apply_veto y
python mkCat_SV3.py --type LRG --combd n --fulld y --clus y --mockrea 1 --univ 2 --verspec fuji --apply_veto y
python mkCat_SV3.py --type LRG --combd n --fulld y --clus y --mockrea 2 --univ 3 --verspec fuji --apply_veto y
python mkCat_SV3.py --type LRG --combd n --fulld y --clus y --mockrea 3 --univ 4 --verspec fuji --apply_veto y
python mkCat_SV3.py --type LRG --combd n --fulld y --clus y --mockrea 4 --univ 5 --verspec fuji --apply_veto y
python mkCat_SV3.py --type LRG --combd n --fulld y --clus y --mockrea 5 --univ 6 --verspec fuji --apply_veto y
python mkCat_SV3.py --type LRG --combd n --fulld y --clus y --mockrea 6 --univ 7 --verspec fuji --apply_veto y
python mkCat_SV3.py --type LRG --combd n --fulld y --clus y --mockrea 7 --univ 8 --verspec fuji --apply_veto y
python mkCat_SV3.py --type LRG --combd n --fulld y --clus y --mockrea 8 --univ 9 --verspec fuji --apply_veto y
python mkCat_SV3.py --type LRG --combd n --fulld y --clus y --mockrea 9 --univ 10 --verspec fuji --apply_veto y
python mkCat_SV3.py --type LRG --combd n --fulld y --clus y --mockrea 10 --univ 11 --verspec fuji --apply_veto y
python mkCat_SV3.py --type LRG --combd n --fulld y --clus y --mockrea 11 --univ 12 --verspec fuji --apply_veto y
python mkCat_SV3.py --type LRG --combd n --fulld y --clus y --mockrea 12 --univ 13 --verspec fuji --apply_veto y
python mkCat_SV3.py --type LRG --combd n --fulld y --clus y --mockrea 13 --univ 14 --verspec fuji --apply_veto y
python mkCat_SV3.py --type LRG --combd n --fulld y --clus y --mockrea 14 --univ 15 --verspec fuji --apply_veto y
python mkCat_SV3.py --type LRG --combd n --fulld y --clus y --mockrea 15 --univ 16 --verspec fuji --apply_veto y
python mkCat_SV3.py --type LRG --combd n --fulld y --clus y --mockrea 16 --univ 17 --verspec fuji --apply_veto y
python mkCat_SV3.py --type LRG --combd n --fulld y --clus y --mockrea 17 --univ 18 --verspec fuji --apply_veto y
python mkCat_SV3.py --type LRG --combd n --fulld y --clus y --mockrea 18 --univ 19 --verspec fuji --apply_veto y
python mkCat_SV3.py --type LRG --combd n --fulld y --clus y --mockrea 19 --univ 20 --verspec fuji --apply_veto y
python mkCat_SV3.py --type LRG --combd n --fulld y --clus y --mockrea 20 --univ 21 --verspec fuji --apply_veto y
python mkCat_SV3.py --type LRG --combd n --fulld y --clus y --mockrea 21 --univ 22 --verspec fuji --apply_veto y
python mkCat_SV3.py --type LRG --combd n --fulld y --clus y --mockrea 22 --univ 23 --verspec fuji --apply_veto y
python mkCat_SV3.py --type LRG --combd n --fulld y --clus y --mockrea 23 --univ 24 --verspec fuji --apply_veto y
python mkCat_SV3.py --type LRG --combd n --fulld y --clus y --mockrea 24 --univ 25 --verspec fuji --apply_veto y
python mkCat_SV3.py --type ELG --combd n --fulld y --clus y --mockrea 0 --univ 1 --verspec fuji --apply_veto y
python mkCat_SV3.py --type ELG --combd n --fulld y --clus y --mockrea 1 --univ 2 --verspec fuji --apply_veto y
python mkCat_SV3.py --type ELG --combd n --fulld y --clus y --mockrea 2 --univ 3 --verspec fuji --apply_veto y
python mkCat_SV3.py --type ELG --combd n --fulld y --clus y --mockrea 3 --univ 4 --verspec fuji --apply_veto y
python mkCat_SV3.py --type ELG --combd n --fulld y --clus y --mockrea 4 --univ 5 --verspec fuji --apply_veto y
python mkCat_SV3.py --type ELG --combd n --fulld y --clus y --mockrea 5 --univ 6 --verspec fuji --apply_veto y
python mkCat_SV3.py --type ELG --combd n --fulld y --clus y --mockrea 6 --univ 7 --verspec fuji --apply_veto y
python mkCat_SV3.py --type ELG --combd n --fulld y --clus y --mockrea 7 --univ 8 --verspec fuji --apply_veto y
python mkCat_SV3.py --type ELG --combd n --fulld y --clus y --mockrea 8 --univ 9 --verspec fuji --apply_veto y
python mkCat_SV3.py --type ELG --combd n --fulld y --clus y --mockrea 9 --univ 10 --verspec fuji --apply_veto y
python mkCat_SV3.py --type ELG --combd n --fulld y --clus y --mockrea 10 --univ 11 --verspec fuji --apply_veto y
python mkCat_SV3.py --type ELG --combd n --fulld y --clus y --mockrea 11 --univ 12 --verspec fuji --apply_veto y
python mkCat_SV3.py --type ELG --combd n --fulld y --clus y --mockrea 12 --univ 13 --verspec fuji --apply_veto y
python mkCat_SV3.py --type ELG --combd n --fulld y --clus y --mockrea 13 --univ 14 --verspec fuji --apply_veto y
python mkCat_SV3.py --type ELG --combd n --fulld y --clus y --mockrea 14 --univ 15 --verspec fuji --apply_veto y
python mkCat_SV3.py --type ELG --combd n --fulld y --clus y --mockrea 15 --univ 16 --verspec fuji --apply_veto y
python mkCat_SV3.py --type ELG --combd n --fulld y --clus y --mockrea 16 --univ 17 --verspec fuji --apply_veto y
python mkCat_SV3.py --type ELG --combd n --fulld y --clus y --mockrea 17 --univ 18 --verspec fuji --apply_veto y
python mkCat_SV3.py --type ELG --combd n --fulld y --clus y --mockrea 18 --univ 19 --verspec fuji --apply_veto y
python mkCat_SV3.py --type ELG --combd n --fulld y --clus y --mockrea 19 --univ 20 --verspec fuji --apply_veto y
python mkCat_SV3.py --type ELG --combd n --fulld y --clus y --mockrea 20 --univ 21 --verspec fuji --apply_veto y
python mkCat_SV3.py --type ELG --combd n --fulld y --clus y --mockrea 21 --univ 22 --verspec fuji --apply_veto y
python mkCat_SV3.py --type ELG --combd n --fulld y --clus y --mockrea 22 --univ 23 --verspec fuji --apply_veto y
python mkCat_SV3.py --type ELG --combd n --fulld y --clus y --mockrea 23 --univ 24 --verspec fuji --apply_veto y
python mkCat_SV3.py --type ELG --combd n --fulld y --clus y --mockrea 24 --univ 25 --verspec fuji --apply_veto y
python mkCat_SV3.py --type QSO --combd n --fulld y --clus y --mockrea 0 --univ 1 --verspec fuji --apply_veto y
python mkCat_SV3.py --type QSO --combd n --fulld y --clus y --mockrea 1 --univ 2 --verspec fuji --apply_veto y
python mkCat_SV3.py --type QSO --combd n --fulld y --clus y --mockrea 2 --univ 3 --verspec fuji --apply_veto y
python mkCat_SV3.py --type QSO --combd n --fulld y --clus y --mockrea 3 --univ 4 --verspec fuji --apply_veto y
python mkCat_SV3.py --type QSO --combd n --fulld y --clus y --mockrea 4 --univ 5 --verspec fuji --apply_veto y
python mkCat_SV3.py --type QSO --combd n --fulld y --clus y --mockrea 5 --univ 6 --verspec fuji --apply_veto y
python mkCat_SV3.py --type QSO --combd n --fulld y --clus y --mockrea 6 --univ 7 --verspec fuji --apply_veto y
python mkCat_SV3.py --type QSO --combd n --fulld y --clus y --mockrea 7 --univ 8 --verspec fuji --apply_veto y
python mkCat_SV3.py --type QSO --combd n --fulld y --clus y --mockrea 8 --univ 9 --verspec fuji --apply_veto y
python mkCat_SV3.py --type QSO --combd n --fulld y --clus y --mockrea 9 --univ 10 --verspec fuji --apply_veto y
python mkCat_SV3.py --type QSO --combd n --fulld y --clus y --mockrea 10 --univ 11 --verspec fuji --apply_veto y
python mkCat_SV3.py --type QSO --combd n --fulld y --clus y --mockrea 11 --univ 12 --verspec fuji --apply_veto y
python mkCat_SV3.py --type QSO --combd n --fulld y --clus y --mockrea 12 --univ 13 --verspec fuji --apply_veto y
python mkCat_SV3.py --type QSO --combd n --fulld y --clus y --mockrea 13 --univ 14 --verspec fuji --apply_veto y
python mkCat_SV3.py --type QSO --combd n --fulld y --clus y --mockrea 14 --univ 15 --verspec fuji --apply_veto y
python mkCat_SV3.py --type QSO --combd n --fulld y --clus y --mockrea 15 --univ 16 --verspec fuji --apply_veto y
python mkCat_SV3.py --type QSO --combd n --fulld y --clus y --mockrea 16 --univ 17 --verspec fuji --apply_veto y
python mkCat_SV3.py --type QSO --combd n --fulld y --clus y --mockrea 17 --univ 18 --verspec fuji --apply_veto y
python mkCat_SV3.py --type QSO --combd n --fulld y --clus y --mockrea 18 --univ 19 --verspec fuji --apply_veto y
python mkCat_SV3.py --type QSO --combd n --fulld y --clus y --mockrea 19 --univ 20 --verspec fuji --apply_veto y
python mkCat_SV3.py --type QSO --combd n --fulld y --clus y --mockrea 20 --univ 21 --verspec fuji --apply_veto y
python mkCat_SV3.py --type QSO --combd n --fulld y --clus y --mockrea 21 --univ 22 --verspec fuji --apply_veto y
python mkCat_SV3.py --type QSO --combd n --fulld y --clus y --mockrea 22 --univ 23 --verspec fuji --apply_veto y
python mkCat_SV3.py --type QSO --combd n --fulld y --clus y --mockrea 23 --univ 24 --verspec fuji --apply_veto y
python mkCat_SV3.py --type QSO --combd n --fulld y --clus y --mockrea 24 --univ 25 --verspec fuji --apply_veto y
