#python ximock.py --type LRG --id 0
#python ximock.py --type LRG --id 1
#python ximock.py --type LRG --id 2
#python ximock.py --type LRG --id 3
#python ximock.py --type LRG --id 4
#python ximock.py --type LRG --id 5
#python ximock.py --type LRG --id 6
#python ximock.py --type LRG --id 7
#python ximock.py --type LRG --id 8
#python ximock.py --type LRG --id 9
#python ximock.py --type LRG --id 10
#python ximock.py --type LRG --id 11
#python ximock.py --type LRG --id 12
#python ximock.py --type LRG --id 13
#python ximock.py --type LRG --id 14
#python ximock.py --type LRG --id 15
#python ximock.py --type LRG --id 16
#python ximock.py --type LRG --id 17
#python ximock.py --type LRG --id 18
#python ximock.py --type LRG --id 19
#python ximock.py --type LRG --id 20
#python ximock.py --type LRG --id 21
#python ximock.py --type LRG --id 22
#python ximock.py --type LRG --id 23
#python ximock.py --type LRG --id 24
python ximock.py --type ELG --id 0
python ximock.py --type ELG --id 1
python ximock.py --type ELG --id 2
python ximock.py --type ELG --id 3
python ximock.py --type ELG --id 4
python ximock.py --type ELG --id 5
python ximock.py --type ELG --id 6
python ximock.py --type ELG --id 7
python ximock.py --type ELG --id 8
python ximock.py --type ELG --id 9
python ximock.py --type ELG --id 10
python ximock.py --type ELG --id 11
python ximock.py --type ELG --id 12
python ximock.py --type ELG --id 13
python ximock.py --type ELG --id 14
python ximock.py --type ELG --id 15
python ximock.py --type ELG --id 16
python ximock.py --type ELG --id 17
python ximock.py --type ELG --id 18
python ximock.py --type ELG --id 19
python ximock.py --type ELG --id 20
python ximock.py --type ELG --id 21
python ximock.py --type ELG --id 22
python ximock.py --type ELG --id 23
python ximock.py --type ELG --id 24
#python ximock.py --type QSO --id 0
#python ximock.py --type QSO --id 1
#python ximock.py --type QSO --id 2
#python ximock.py --type QSO --id 3
#python ximock.py --type QSO --id 4
#python ximock.py --type QSO --id 5
#python ximock.py --type QSO --id 6
#python ximock.py --type QSO --id 7
#python ximock.py --type QSO --id 8
#python ximock.py --type QSO --id 9
#python ximock.py --type QSO --id 10
#python ximock.py --type QSO --id 11
#python ximock.py --type QSO --id 12
#python ximock.py --type QSO --id 13
#python ximock.py --type QSO --id 14
#python ximock.py --type QSO --id 15
#python ximock.py --type QSO --id 16
#python ximock.py --type QSO --id 17
#python ximock.py --type QSO --id 18
#python ximock.py --type QSO --id 19
#python ximock.py --type QSO --id 20
#python ximock.py --type QSO --id 21
#python ximock.py --type QSO --id 22
#python ximock.py --type QSO --id 23
#python ximock.py --type QSO --id 24
