python xifirstgen.py --type LRG --id 0 --idran 0
python xifirstgen.py --type LRG --id 1 --idran 1
python xifirstgen.py --type LRG --id 2 --idran 2
python xifirstgen.py --type LRG --id 3 --idran 3
python xifirstgen.py --type LRG --id 4 --idran 4
python xifirstgen.py --type LRG --id 5 --idran 5
python xifirstgen.py --type LRG --id 6 --idran 6
python xifirstgen.py --type LRG --id 7 --idran 7
python xifirstgen.py --type LRG --id 8 --idran 8
python xifirstgen.py --type LRG --id 9 --idran 9
python xifirstgen.py --type LRG --id 10 --idran 0
python xifirstgen.py --type LRG --id 11 --idran 1
python xifirstgen.py --type LRG --id 12 --idran 2
python xifirstgen.py --type LRG --id 13 --idran 3
python xifirstgen.py --type LRG --id 14 --idran 4
python xifirstgen.py --type LRG --id 15 --idran 5
python xifirstgen.py --type LRG --id 16 --idran 6
python xifirstgen.py --type LRG --id 17 --idran 7
python xifirstgen.py --type LRG --id 18 --idran 8
python xifirstgen.py --type LRG --id 19 --idran 9
python xifirstgen.py --type LRG --id 20 --idran 0
python xifirstgen.py --type LRG --id 21 --idran 1
python xifirstgen.py --type LRG --id 22 --idran 2
python xifirstgen.py --type LRG --id 23 --idran 3
python xifirstgen.py --type LRG --id 24 --idran 4
