python mkMock_SV3.py --type LRG --verspec mock --combd n --fulld y --clus y --id 2
python mkMock_SV3.py --type LRG --verspec mock --combd n --fulld y --clus y --id 3
python mkMock_SV3.py --type LRG --verspec mock --combd n --fulld y --clus y --id 4
python mkMock_SV3.py --type LRG --verspec mock --combd n --fulld y --clus y --id 5
python mkMock_SV3.py --type LRG --verspec mock --combd n --fulld y --clus y --id 6
python mkMock_SV3.py --type LRG --verspec mock --combd n --fulld y --clus y --id 7
python mkMock_SV3.py --type LRG --verspec mock --combd n --fulld y --clus y --id 8
python mkMock_SV3.py --type LRG --verspec mock --combd n --fulld y --clus y --id 9
python mkMock_SV3.py --type LRG --verspec mock --combd n --fulld y --clus y --id 10
python mkMock_SV3.py --type LRG --verspec mock --combd n --fulld y --clus y --id 11
python mkMock_SV3.py --type LRG --verspec mock --combd n --fulld y --clus y --id 12
python mkMock_SV3.py --type LRG --verspec mock --combd n --fulld y --clus y --id 13
python mkMock_SV3.py --type LRG --verspec mock --combd n --fulld y --clus y --id 14
python mkMock_SV3.py --type LRG --verspec mock --combd n --fulld y --clus y --id 15
python mkMock_SV3.py --type LRG --verspec mock --combd n --fulld y --clus y --id 16
python mkMock_SV3.py --type LRG --verspec mock --combd n --fulld y --clus y --id 17
python mkMock_SV3.py --type LRG --verspec mock --combd n --fulld y --clus y --id 18
python mkMock_SV3.py --type LRG --verspec mock --combd n --fulld y --clus y --id 19
python mkMock_SV3.py --type LRG --verspec mock --combd n --fulld y --clus y --id 20
python mkMock_SV3.py --type LRG --verspec mock --combd n --fulld y --clus y --id 21
python mkMock_SV3.py --type LRG --verspec mock --combd n --fulld y --clus y --id 22
python mkMock_SV3.py --type LRG --verspec mock --combd n --fulld y --clus y --id 23
python mkMock_SV3.py --type LRG --verspec mock --combd n --fulld y --clus y --id 24
