python mkMock_SV3_randoms.py --type ELG --verspec mock --fullr y --clusran y --id 0
python mkMock_SV3_randoms.py --type ELG --verspec mock --fullr y --clusran y --id 1
python mkMock_SV3_randoms.py --type ELG --verspec mock --fullr y --clusran y --id 2
python mkMock_SV3_randoms.py --type ELG --verspec mock --fullr y --clusran y --id 3
python mkMock_SV3_randoms.py --type ELG --verspec mock --fullr y --clusran y --id 4
python mkMock_SV3_randoms.py --type ELG --verspec mock --fullr y --clusran y --id 5
python mkMock_SV3_randoms.py --type ELG --verspec mock --fullr y --clusran y --id 6
python mkMock_SV3_randoms.py --type ELG --verspec mock --fullr y --clusran y --id 7
python mkMock_SV3_randoms.py --type ELG --verspec mock --fullr y --clusran y --id 8
python mkMock_SV3_randoms.py --type ELG --verspec mock --fullr y --clusran y --id 9
python mkMock_SV3_randoms.py --type ELG --verspec mock --fullr y --clusran y --id 10
python mkMock_SV3_randoms.py --type ELG --verspec mock --fullr y --clusran y --id 11
python mkMock_SV3_randoms.py --type ELG --verspec mock --fullr y --clusran y --id 12
python mkMock_SV3_randoms.py --type ELG --verspec mock --fullr y --clusran y --id 13
python mkMock_SV3_randoms.py --type ELG --verspec mock --fullr y --clusran y --id 14
python mkMock_SV3_randoms.py --type ELG --verspec mock --fullr y --clusran y --id 15
python mkMock_SV3_randoms.py --type ELG --verspec mock --fullr y --clusran y --id 16
python mkMock_SV3_randoms.py --type ELG --verspec mock --fullr y --clusran y --id 17
python mkMock_SV3_randoms.py --type ELG --verspec mock --fullr y --clusran y --id 18
python mkMock_SV3_randoms.py --type ELG --verspec mock --fullr y --clusran y --id 19
python mkMock_SV3_randoms.py --type ELG --verspec mock --fullr y --clusran y --id 20
python mkMock_SV3_randoms.py --type ELG --verspec mock --fullr y --clusran y --id 21
python mkMock_SV3_randoms.py --type ELG --verspec mock --fullr y --clusran y --id 22
python mkMock_SV3_randoms.py --type ELG --verspec mock --fullr y --clusran y --id 23
python mkMock_SV3_randoms.py --type ELG --verspec mock --fullr y --clusran y --id 24
