#python mkMock_SV3_randoms.py --type dark --verspec mock --combr y --cutran y --ranmtl y --id 0
#python mkMock_SV3_randoms.py --type dark --verspec mock --combr y --cutran y --ranmtl y --id 1
#python mkMock_SV3_randoms.py --type dark --verspec mock --combr y --cutran y --ranmtl y --id 2
#python mkMock_SV3_randoms.py --type dark --verspec mock --combr y --cutran y --ranmtl y --id 3
#python mkMock_SV3_randoms.py --type dark --verspec mock --combr y --cutran y --ranmtl y --id 4
#python mkMock_SV3_randoms.py --type dark --verspec mock --combr y --cutran y --ranmtl y --id 5
#python mkMock_SV3_randoms.py --type dark --verspec mock --combr y --cutran y --ranmtl y --id 6
#python mkMock_SV3_randoms.py --type dark --verspec mock --combr y --cutran y --ranmtl y --id 7
#python mkMock_SV3_randoms.py --type dark --verspec mock --combr y --cutran y --ranmtl y --id 8
#python mkMock_SV3_randoms.py --type dark --verspec mock --combr y --cutran y --ranmtl y --id 9
#python mkMock_SV3_randoms.py --type dark --verspec mock --combr y --cutran y --ranmtl y --id 10
#python mkMock_SV3_randoms.py --type dark --verspec mock --combr y --cutran y --ranmtl y --id 11
#python mkMock_SV3_randoms.py --type dark --verspec mock --combr y --cutran y --ranmtl y --id 12
#python mkMock_SV3_randoms.py --type dark --verspec mock --combr y --cutran y --ranmtl y --id 13
#python mkMock_SV3_randoms.py --type dark --verspec mock --combr y --cutran y --ranmtl y --id 14
#python mkMock_SV3_randoms.py --type dark --verspec mock --combr y --cutran y --ranmtl y --id 15
#python mkMock_SV3_randoms.py --type dark --verspec mock --combr y --cutran y --ranmtl y --id 16
#python mkMock_SV3_randoms.py --type dark --verspec mock --combr y --cutran y --ranmtl y --id 17
python mkMock_SV3_randoms.py --type dark --verspec mock --combr y --cutran y --ranmtl y --id 18
python mkMock_SV3_randoms.py --type dark --verspec mock --combr y --cutran y --ranmtl y --id 19
python mkMock_SV3_randoms.py --type dark --verspec mock --combr y --cutran y --ranmtl y --id 20
python mkMock_SV3_randoms.py --type dark --verspec mock --combr y --cutran y --ranmtl y --id 21
python mkMock_SV3_randoms.py --type dark --verspec mock --combr y --cutran y --ranmtl y --id 22
python mkMock_SV3_randoms.py --type dark --verspec mock --combr y --cutran y --ranmtl y --id 23
python mkMock_SV3_randoms.py --type dark --verspec mock --combr y --cutran y --ranmtl y --id 24
