python xirunpc.py --nran 20 --univ 1 --tracer LRG --mockrea 0 --verspec fuji --bin_type log --weight_type default
python xirunpc.py --nran 20 --univ 1 --tracer LRG --mockrea 0 --verspec fuji --bin_type lin --weight_type default
python xirunpc.py --nran 20 --univ 1 --tracer ELG --mockrea 0 --verspec fuji --bin_type log --weight_type default
python xirunpc.py --nran 20 --univ 1 --tracer ELG --mockrea 0 --verspec fuji --bin_type lin --weight_type default
python xirunpc.py --nran 20 --univ 1 --tracer QSO --mockrea 0 --verspec fuji --bin_type log --weight_type default
python xirunpc.py --nran 20 --univ 1 --tracer QSO --mockrea 0 --verspec fuji --bin_type lin --weight_type default
python xirunpc.py --nran 20 --univ 1 --tracer LRG --mockrea 0 --verspec fuji --bin_type log --weight_type default_angular_bitwise
python xirunpc.py --nran 20 --univ 1 --tracer LRG --mockrea 0 --verspec fuji --bin_type lin --weight_type default_angular_bitwise
python xirunpc.py --nran 20 --univ 1 --tracer ELG --mockrea 0 --verspec fuji --bin_type log --weight_type default_angular_bitwise
python xirunpc.py --nran 20 --univ 1 --tracer ELG --mockrea 0 --verspec fuji --bin_type lin --weight_type default_angular_bitwise
python xirunpc.py --nran 20 --univ 1 --tracer QSO --mockrea 0 --verspec fuji --bin_type log --weight_type default_angular_bitwise
python xirunpc.py --nran 20 --univ 1 --tracer QSO --mockrea 0 --verspec fuji --bin_type lin --weight_type default_angular_bitwise
python xirunpc.py --nran 20 --univ 1 --tracer LRG --mockrea 0 --verspec fuji --bin_type log --weight_type default_bitwise
python xirunpc.py --nran 20 --univ 1 --tracer LRG --mockrea 0 --verspec fuji --bin_type lin --weight_type default_bitwise
python xirunpc.py --nran 20 --univ 1 --tracer ELG --mockrea 0 --verspec fuji --bin_type log --weight_type default_bitwise
python xirunpc.py --nran 20 --univ 1 --tracer ELG --mockrea 0 --verspec fuji --bin_type lin --weight_type default_bitwise
python xirunpc.py --nran 20 --univ 1 --tracer QSO --mockrea 0 --verspec fuji --bin_type log --weight_type default_bitwise
python xirunpc.py --nran 20 --univ 1 --tracer QSO --mockrea 0 --verspec fuji --bin_type lin --weight_type default_bitwise
python xirunpc.py --nran 20 --univ 1 --tracer LRG --mockrea 0 --verspec fuji --bin_type log --weight_type default_angular
python xirunpc.py --nran 20 --univ 1 --tracer LRG --mockrea 0 --verspec fuji --bin_type lin --weight_type default_angular
python xirunpc.py --nran 20 --univ 1 --tracer ELG --mockrea 0 --verspec fuji --bin_type log --weight_type default_angular
python xirunpc.py --nran 20 --univ 1 --tracer ELG --mockrea 0 --verspec fuji --bin_type lin --weight_type default_angular
python xirunpc.py --nran 20 --univ 1 --tracer QSO --mockrea 0 --verspec fuji --bin_type log --weight_type default_angular
python xirunpc.py --nran 20 --univ 1 --tracer QSO --mockrea 0 --verspec fuji --bin_type lin --weight_type default_angular
