srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python /pscratch/sd/a/acarnero/codes/LSS/scripts/getpotaY1_mock.py --realization 4 --prog BRIGHT --mock_version BGS
srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python /pscratch/sd/a/acarnero/codes/LSS/scripts/getpotaY1_mock.py --realization 5 --prog BRIGHT --mock_version BGS
srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python /pscratch/sd/a/acarnero/codes/LSS/scripts/getpotaY1_mock.py --realization 6 --prog BRIGHT --mock_version BGS
srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python /pscratch/sd/a/acarnero/codes/LSS/scripts/getpotaY1_mock.py --realization 7 --prog BRIGHT --mock_version BGS
srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python /pscratch/sd/a/acarnero/codes/LSS/scripts/getpotaY1_mock.py --realization 8 --prog BRIGHT --mock_version BGS
srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python /pscratch/sd/a/acarnero/codes/LSS/scripts/getpotaY1_mock.py --realization 9 --prog BRIGHT --mock_version BGS
srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python /pscratch/sd/a/acarnero/codes/LSS/scripts/getpotaY1_mock.py --realization 10 --prog BRIGHT --mock_version BGS
srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python /pscratch/sd/a/acarnero/codes/LSS/scripts/getpotaY1_mock.py --realization 11 --prog BRIGHT --mock_version BGS
srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python /pscratch/sd/a/acarnero/codes/LSS/scripts/getpotaY1_mock.py --realization 12 --prog BRIGHT --mock_version BGS
srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python /pscratch/sd/a/acarnero/codes/LSS/scripts/getpotaY1_mock.py --realization 13 --prog BRIGHT --mock_version BGS
srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python /pscratch/sd/a/acarnero/codes/LSS/scripts/getpotaY1_mock.py --realization 14 --prog BRIGHT --mock_version BGS
srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python /pscratch/sd/a/acarnero/codes/LSS/scripts/getpotaY1_mock.py --realization 15 --prog BRIGHT --mock_version BGS
srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python /pscratch/sd/a/acarnero/codes/LSS/scripts/getpotaY1_mock.py --realization 16 --prog BRIGHT --mock_version BGS
srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python /pscratch/sd/a/acarnero/codes/LSS/scripts/getpotaY1_mock.py --realization 17 --prog BRIGHT --mock_version BGS
srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python /pscratch/sd/a/acarnero/codes/LSS/scripts/getpotaY1_mock.py --realization 18 --prog BRIGHT --mock_version BGS
srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python /pscratch/sd/a/acarnero/codes/LSS/scripts/getpotaY1_mock.py --realization 19 --prog BRIGHT --mock_version BGS
srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python /pscratch/sd/a/acarnero/codes/LSS/scripts/getpotaY1_mock.py --realization 20 --prog BRIGHT --mock_version BGS
srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python /pscratch/sd/a/acarnero/codes/LSS/scripts/getpotaY1_mock.py --realization 21 --prog BRIGHT --mock_version BGS
srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python /pscratch/sd/a/acarnero/codes/LSS/scripts/getpotaY1_mock.py --realization 22 --prog BRIGHT --mock_version BGS
srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python /pscratch/sd/a/acarnero/codes/LSS/scripts/getpotaY1_mock.py --realization 23 --prog BRIGHT --mock_version BGS
srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python /pscratch/sd/a/acarnero/codes/LSS/scripts/getpotaY1_mock.py --realization 24 --prog BRIGHT --mock_version BGS
