#srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python /pscratch/sd/a/acarnero/codes/LSS/scripts/getpotaY1_mock.py --realization 0 --secgen_ver AbacusSummit_v3_1
#srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python /pscratch/sd/a/acarnero/codes/LSS/scripts/getpotaY1_mock.py --realization 1 --secgen_ver AbacusSummit_v3_1
#srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python /pscratch/sd/a/acarnero/codes/LSS/scripts/getpotaY1_mock.py --realization 2 --secgen_ver AbacusSummit_v3_1
#srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python /pscratch/sd/a/acarnero/codes/LSS/scripts/getpotaY1_mock.py --realization 3 --secgen_ver AbacusSummit_v3_1
#srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python /pscratch/sd/a/acarnero/codes/LSS/scripts/getpotaY1_mock.py --realization 4 --secgen_ver AbacusSummit_v3_1
#srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python /pscratch/sd/a/acarnero/codes/LSS/scripts/getpotaY1_mock.py --realization 5 --secgen_ver AbacusSummit_v3_1
srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python /pscratch/sd/a/acarnero/codes/LSS/scripts/getpotaY1_mock.py --realization 6 --secgen_ver AbacusSummit_v3_1
srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python /pscratch/sd/a/acarnero/codes/LSS/scripts/getpotaY1_mock.py --realization 7 --secgen_ver AbacusSummit_v3_1
srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python /pscratch/sd/a/acarnero/codes/LSS/scripts/getpotaY1_mock.py --realization 8 --secgen_ver AbacusSummit_v3_1
srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python /pscratch/sd/a/acarnero/codes/LSS/scripts/getpotaY1_mock.py --realization 9 --secgen_ver AbacusSummit_v3_1
srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python /pscratch/sd/a/acarnero/codes/LSS/scripts/getpotaY1_mock.py --realization 10 --secgen_ver AbacusSummit_v3_1
srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python /pscratch/sd/a/acarnero/codes/LSS/scripts/getpotaY1_mock.py --realization 11 --secgen_ver AbacusSummit_v3_1
srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python /pscratch/sd/a/acarnero/codes/LSS/scripts/getpotaY1_mock.py --realization 12 --secgen_ver AbacusSummit_v3_1
srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python /pscratch/sd/a/acarnero/codes/LSS/scripts/getpotaY1_mock.py --realization 13 --secgen_ver AbacusSummit_v3_1
srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python /pscratch/sd/a/acarnero/codes/LSS/scripts/getpotaY1_mock.py --realization 14 --secgen_ver AbacusSummit_v3_1
srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python /pscratch/sd/a/acarnero/codes/LSS/scripts/getpotaY1_mock.py --realization 15 --secgen_ver AbacusSummit_v3_1
srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python /pscratch/sd/a/acarnero/codes/LSS/scripts/getpotaY1_mock.py --realization 16 --secgen_ver AbacusSummit_v3_1
srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python /pscratch/sd/a/acarnero/codes/LSS/scripts/getpotaY1_mock.py --realization 17 --secgen_ver AbacusSummit_v3_1
srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python /pscratch/sd/a/acarnero/codes/LSS/scripts/getpotaY1_mock.py --realization 18 --secgen_ver AbacusSummit_v3_1
srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python /pscratch/sd/a/acarnero/codes/LSS/scripts/getpotaY1_mock.py --realization 19 --secgen_ver AbacusSummit_v3_1
srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python /pscratch/sd/a/acarnero/codes/LSS/scripts/getpotaY1_mock.py --realization 20 --secgen_ver AbacusSummit_v3_1
srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python /pscratch/sd/a/acarnero/codes/LSS/scripts/getpotaY1_mock.py --realization 21 --secgen_ver AbacusSummit_v3_1
srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python /pscratch/sd/a/acarnero/codes/LSS/scripts/getpotaY1_mock.py --realization 22 --secgen_ver AbacusSummit_v3_1
srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python /pscratch/sd/a/acarnero/codes/LSS/scripts/getpotaY1_mock.py --realization 23 --secgen_ver AbacusSummit_v3_1
srun -N 1 -C cpu  -t 01:00:00 -q interactive --account desi python /pscratch/sd/a/acarnero/codes/LSS/scripts/getpotaY1_mock.py --realization 24 --secgen_ver AbacusSummit_v3_1
